# custom difficulty
custom.baseSpeed=5
custom.factor=4
custom.count=10
custom.shootRate=0.07

# tank shoot strategy
# 1. DefaultShootStrategy
# 2. FourDirShootStrategy
shoot.strategy=FourDirShootStrategy

# collision kinds
collision.kinds=BulletTankCollision,BulletWallCollision,TankWallCollision